// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brhqvrkvezsdithiegzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyaHF2cmt2ZXpzZGl0aGllZ3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjIwMDEsImV4cCI6MjA2NTgzODAwMX0.ZDuPJfDz1tC35RaNVW8QsZ-cXLPv5ZFWRPfJc2eSSUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);